version: '3.4'

services:
  catalogdb:
    image: mongo
  basketdb:
    image: redis:alpine #alpine is a light weight image

    #TEST PART
  discountdb:
    image: postgres #alpine is a light weight image


  portainer:
    image: portainer/portainer-ce
  pgadmin:
    image: dpage/pgadmin4

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services\Catalog\Catalog.API\Dockerfile
      #one of the important part
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:

  #Volumes: basically datastore that are outside of the containers and exist on the host file system.

